### ISSUE TITLE
Typo in image filename

### ISSUE THREAD

**Issue by gxavier38** [CIDARLAB/knox#1]
The file blunt_end_restriction_enzyme_**clevage**_site.svg is misspelt and therefore shows a user_defined.svg symbol instead.
File is at `knox/src/main/resources/static/img/sbol/blunt_end_restriction_enzyme_clevage_site.svg`

**Comment by evanbowman** [comment]
Whoops, this might have been my fault, when I was doing the UI I downloaded the svg files from sbolstandard.org, but @nroehner pointed out to me that the internal name used by knox to represent blunt end restriction sites was called blunt_end_restriction_enzyme_clevage_site (the proper full name) and would not match the abbreviated filename used by sbolstandard (blunt_restriction_site.svg), so I renamed the file, _incorrectly_
