### ISSUE TITLE
one-or-more(zero-or-more)) missing accept node 

### ISSUE THREAD

**Issue by dany-fu** [CIDARLAB/knox#11]
I tried to replicate this on the UI by applying the operators manually and Knox became unresponsive, but I didn't get any error logs. 

The missing accept node bug can be replicated with this SBOL on the `combinatorial_sbol` branch

[oneormore_zeroormore.txt](https://github.com/CIDARLAB/knox/files/2946802/oneormore_zeroormore.txt)

**Comment by nroehner** [comment]
This should now be fixed as commit 0b675ed2a23ae8e2bc3c337507679b8c87d99a05. There was a bug in the removeBlankCycles method of the NodeSpace class where the types of nodes in blank edge cycles failed to be carried over when transforming and removing the blank edge cycles.
