### ISSUE TITLE
Applying the OROperator with an empty outputSpace to represent zeroOrOne

### ISSUE THREAD

**Issue by dany-fu** [CIDARLAB/knox#7]
Expected: two edges between two nodes
Actual: one edge 

This can be reproduced on the current `combinatorial_sbol` branch

[constellation_optional_one.txt](https://github.com/CIDARLAB/knox/files/2920940/constellation_optional_one.txt)

**Comment by nroehner** [comment]
Please see my recent commit

https://github.com/CIDARLAB/knox/commit/ffd6bc03ef02621c362d1d307ce8ae0a8cf09a92. 

I think this fixes the issue by a adding nodespace with blank edge to the list of input spaces when applyOperator is called with the zero-or-one operator.
